import React from 'react';
import { clientMockService } from '../../services/clientMockService';
import { Briefcase, CheckCircle2, Clock, DollarSign, MessageSquare, FileText, ChevronRight, Zap, AlertTriangle, Users } from 'lucide-react';

interface ClientOverviewProps {
  setActiveView: (view: string) => void;
  setSelectedProjectId: (id: string) => void;
}

export const ClientOverview: React.FC<ClientOverviewProps> = ({
  setActiveView,
  setSelectedProjectId
}) => {
  const projects = clientMockService.getProjects();
  const notifications = clientMockService.getNotifications();
  const unreadNotifications = notifications.filter(n => n.unread);
  const activeProj = projects.find(p => p.status === 'Active') || projects[0];

  const totalBudget = projects.reduce((acc, p) => acc + p.budget, 0);
  const totalPaid = projects.reduce((acc, p) => acc + p.spent, 0);
  const totalEscrow = projects.reduce((acc, p) => acc + p.escrow.remaining, 0);
  const reviewDocsCount = projects.reduce((acc, p) => acc + p.documents.length, 0);

  // Recommendations mock
  const recommendedPros = [
    { name: 'Ananya Roy', role: 'Architect', rating: 4.9, match: '98%', image: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=80&h=80' },
    { name: 'David Miller', role: 'Contractor', rating: 4.7, match: '92%', image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=80&h=80' }
  ];

  const handleActionClick = (notif: any) => {
    clientMockService.markNotificationRead(notif.id);
    if (notif.actionView === 'project-workspace' && notif.projectId) {
      setSelectedProjectId(notif.projectId);
      setActiveView('project-workspace');
    } else {
      setActiveView('notifications');
    }
  };

  return (
    <div className="space-y-6">
      {/* Welcome & Info */}
      <div className="bg-[#FFF7ED] border border-[#FED7AA] p-6 rounded-3xl flex justify-between items-center shadow-sm">
        <div>
          <h2 className="text-xl font-black text-brandDark-black font-display">Client Command Center</h2>
          <p className="text-xs font-bold text-[#EA580C] mt-1">Track architectural plans, monitor construction milestones, and release escrow payments securely.</p>
        </div>
        <div className="hidden sm:block text-xs bg-white border border-[#FED7AA] px-4 py-2 rounded-2xl text-slate-700 font-bold">
          Account Tier: <strong className="text-primary font-black">Escrow Protected</strong>
        </div>
      </div>

      {/* Safety Notice */}
      <div className="bg-blue-50 border border-blue-200 p-4 rounded-2xl flex items-start space-x-3">
        <Zap className="w-5 h-5 text-blue-500 flex-shrink-0 mt-0.5" />
        <div className="text-xs font-bold text-blue-800">
          <span className="uppercase tracking-wider font-extrabold block mb-0.5 text-[10px]">AI Responsibility Disclaimer</span>
          All designs, materials recommendations, and budget projections generated by BuildPilot AI models are advisory tools. Verify structural parameters and specifications with a certified professional before approving project milestones.
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">
        {[
          { label: 'Total Projects', val: projects.length, icon: <Briefcase className="w-5 h-5 text-blue-500" />, note: `${projects.filter(p => p.status === 'Active').length} Active projects` },
          { label: 'Project Budget', val: `₹${totalBudget.toLocaleString()}`, icon: <DollarSign className="w-5 h-5 text-green-500" />, note: `₹${totalPaid.toLocaleString()} paid so far` },
          { label: 'Held in Escrow', val: `₹${totalEscrow.toLocaleString()}`, icon: <CheckCircle2 className="w-5 h-5 text-[#EA580C]" />, note: 'Secured funds' },
          { label: 'Documents Library', val: reviewDocsCount, icon: <FileText className="w-5 h-5 text-purple-500" />, note: 'Contracts & blueprints' }
        ].map((k, i) => (
          <div key={i} className="bg-white border border-brandLight-border p-5 rounded-3xl shadow-sm hover:shadow-md transition-all duration-300 flex flex-col justify-between space-y-4">
            <div className="flex justify-between items-start">
              <span className="text-[10px] text-slate-400 font-black uppercase tracking-widest">{k.label}</span>
              <div className="p-2 rounded-2xl bg-slate-50 border border-slate-100">{k.icon}</div>
            </div>
            <div>
              <span className="text-2xl font-black text-brandDark-black block tracking-tight font-mono">{k.val}</span>
              <span className="text-[10px] text-slate-500 font-bold block mt-0.5">{k.note}</span>
            </div>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* LEFT COLUMN: ACTIVE PROJECT SUMMARY & ACTION CENTER */}
        <div className="lg:col-span-2 space-y-6">
          {/* Active Project Summary */}
          {activeProj && (
            <div className="bg-white border border-brandLight-border p-6 rounded-3xl space-y-4 shadow-sm">
              <div className="flex justify-between items-start pb-2 border-b border-slate-100">
                <div>
                  <span className="text-[9px] bg-primary/10 border border-primary/20 text-primary px-2 py-0.5 rounded-lg uppercase tracking-wider font-black">Active Build</span>
                  <h3 className="text-base font-black text-brandDark-black mt-1.5">{activeProj.name}</h3>
                </div>
                <button
                  onClick={() => {
                    setSelectedProjectId(activeProj.id);
                    setActiveView('project-workspace');
                  }}
                  className="px-4 py-2 border border-slate-200 hover:border-slate-350 hover:bg-slate-50 text-xs font-bold text-slate-600 rounded-xl transition-all"
                >
                  Manage Project
                </button>
              </div>

              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 text-xs font-bold text-slate-500 pt-2">
                <div>
                  <span className="text-[9px] text-slate-400 block uppercase font-black">Budget</span>
                  <span className="text-brandDark-black font-black font-mono">₹{activeProj.budget.toLocaleString()}</span>
                </div>
                <div>
                  <span className="text-[9px] text-slate-400 block uppercase font-black">Spent</span>
                  <span className="text-brandDark-black font-black font-mono">₹{activeProj.spent.toLocaleString()}</span>
                </div>
                <div>
                  <span className="text-[9px] text-slate-400 block uppercase font-black">Lead Pro</span>
                  <span className="text-brandDark-black font-black">{activeProj.professionalName}</span>
                </div>
                <div>
                  <span className="text-[9px] text-slate-400 block uppercase font-black">Next Deadline</span>
                  <span className="text-brandDark-black font-black font-mono">{activeProj.deadline}</span>
                </div>
              </div>

              <div className="space-y-1.5 pt-2">
                <div className="flex justify-between text-xs font-bold text-slate-500">
                  <span>Milestone progress: <strong className="text-brandDark-black font-black">{activeProj.currentMilestone}</strong></span>
                  <span>{activeProj.progress}%</span>
                </div>
                <div className="w-full bg-slate-100 h-2 rounded-full overflow-hidden shadow-inner">
                  <div className="bg-primary h-full rounded-full transition-all duration-500" style={{ width: `${activeProj.progress}%` }}></div>
                </div>
              </div>
            </div>
          )}

          {/* Action Center */}
          <div className="bg-white border border-brandLight-border p-6 rounded-3xl space-y-4 shadow-sm">
            <h3 className="text-xs font-black text-brandDark-black uppercase tracking-wider flex items-center space-x-1.5 pb-2 border-b border-slate-100">
              <AlertTriangle className="w-4 h-4 text-primary" />
              <span>Requires Your Attention</span>
            </h3>

            <div className="space-y-2.5">
              {unreadNotifications.map((n) => (
                <button
                  key={n.id}
                  onClick={() => handleActionClick(n)}
                  className="w-full text-left p-3.5 bg-[#FFF7ED]/30 hover:bg-[#FFF7ED]/60 border border-[#FED7AA]/60 hover:border-[#FED7AA] text-xs font-bold text-[#9A3412] rounded-2xl flex justify-between items-center transition-all group"
                >
                  <span className="flex items-center space-x-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-primary animate-pulse"></span>
                    <span>{n.text}</span>
                  </span>
                  <span className="px-3 py-1 bg-white hover:bg-slate-50 border border-[#FED7AA]/70 rounded-xl text-[10px] font-black uppercase text-primary transition-all group-hover:shadow-sm">
                    Review Now
                  </span>
                </button>
              ))}
              {unreadNotifications.length === 0 && (
                <div className="text-center py-6 text-xs font-bold text-slate-400">
                  You're all caught up. No pending approvals or action items.
                </div>
              )}
            </div>
          </div>
        </div>

        {/* RIGHT COLUMN: EVENTS & RECOMMENDED PROS */}
        <div className="space-y-6">
          {/* Upcoming events */}
          <div className="bg-white border border-brandLight-border p-6 rounded-3xl space-y-4 shadow-sm">
            <h3 className="text-xs font-black text-brandDark-black uppercase tracking-wider pb-2 border-b border-slate-100 flex items-center space-x-1.5">
              <Clock className="w-4 h-4 text-primary" />
              <span>Upcoming Project Events</span>
            </h3>
            <div className="space-y-3.5">
              {[
                { date: 'Aug 18', type: 'Site Visit', label: 'Plinth foundation review at site', time: '10:00 AM' },
                { date: 'Aug 20', type: 'Design Review', label: 'Cabinet panel selection walkthrough', time: '04:30 PM' },
                { date: 'Aug 24', type: 'Deadline', label: 'Tiling stage target completion', time: '05:00 PM' }
              ].map((ev, i) => (
                <div key={i} className="p-3 bg-slate-50 border border-slate-100 rounded-2xl text-xs font-bold text-slate-500 space-y-1.5">
                  <div className="flex justify-between items-center">
                    <span className={`text-[9px] px-1.5 py-0.5 rounded font-black uppercase ${
                      ev.type === 'Site Visit' ? 'bg-orange-50 text-orange-600 border border-orange-200/50' : 'bg-blue-50 text-blue-600 border border-blue-200/50'
                    }`}>
                      {ev.type}
                    </span>
                    <span className="font-mono text-brandDark-black">{ev.date}</span>
                  </div>
                  <p className="text-brandDark-black text-[11px] leading-tight font-black">{ev.label}</p>
                  <span className="text-[10px] text-slate-400 block font-mono">{ev.time}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Recommended Pros */}
          <div className="bg-white border border-brandLight-border p-6 rounded-3xl space-y-4 shadow-sm">
            <h3 className="text-xs font-black text-brandDark-black uppercase tracking-wider pb-2 border-b border-slate-100 flex items-center space-x-1.5">
              <Users className="w-4 h-4 text-primary" />
              <span>Hiring Recommendations</span>
            </h3>
            <div className="space-y-3">
              {recommendedPros.map((pro, i) => (
                <div key={i} className="p-3 bg-slate-50 border border-slate-100 rounded-2xl flex justify-between items-center hover:border-slate-200 transition-all">
                  <div className="flex items-center space-x-3">
                    <img src={pro.image} alt={pro.name} className="w-10 h-10 rounded-full object-cover border border-slate-200" />
                    <div>
                      <span className="text-xs font-black text-brandDark-black block">{pro.name}</span>
                      <span className="text-[10px] text-slate-400 font-bold block">{pro.role} • {pro.rating} ★</span>
                    </div>
                  </div>
                  <button
                    onClick={() => setActiveView('marketplace')}
                    className="text-[10px] font-black text-primary hover:text-primary-dark flex items-center space-x-0.5"
                  >
                    <span>Contact</span>
                    <ChevronRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
